version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: ./packages/api/Dockerfile
      args:
        - PROD_DATABASE_URL=${PROD_DATABASE_URL}
      target: 'production'
  client:
    build:
      context: ./
      dockerfile: ./packages/client/Dockerfile
      target: 'production'
  database:
    build:
      context: ./
      dockerfile: ./packages/database/Dockerfile
      args:
        - POSTGRES_USER=${PROD_POSTGRES_USER}
        - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
        - POSTGRES_DB=${PROD_POSTGRES_DB}
  proxy:
    build:
      context: ./
      dockerfile: ./packages/proxy/Dockerfile
