version: "3.7"

networks:
  keepcouncil:

services:
  api:
    image: keepcouncil-api
    container_name: api
    restart: unless-stopped
    networks:
      - keepcouncil
    depends_on:
      - database
  client:
    image: keepcouncil-client
    container_name: client
    restart: unless-stopped
    networks:
      - keepcouncil
    depends_on:
      - api
  database:
    image: keepcouncil-database
    container_name: database
    restart: unless-stopped
    networks:
      - keepcouncil
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  proxy:
    image: keepcouncil-proxy
    container_name: proxy
    restart: unless-stopped
    networks:
      - keepcouncil
    volumes:
      - ./packages/proxy:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
