version: "3.7"

services:
  api:
    build:
      args:
        - DEV_DATABASE_URL=${DEV_DATABASE_URL}
      target: 'development'
    volumes:
      - ./packages/api/src:/usr/src/app/api/src
      - ./packages/api/knexfile.js:/usr/src/app/api/knexfile.js
      - ./packages/api/migrations:/usr/src/app/api/migrations
    ports:
      - '3001:3001'
  client:
    build:
      target: 'development'
    volumes:
      - ./packages/client:/usr/src/app/client
    ports:
      - '3000:3000'
      - '24678:24678'
    command: sh -c "./wait-for-it.sh api:3001 --strict --timeout=0 -- yarn dev"
  database:
    build:
      args:
        - POSTGRES_USER=${DEV_POSTGRES_USER}
        - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
        - POSTGRES_DB=${DEV_POSTGRES_DB}
    ports:
      - '15432:5432'
