version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: ./packages/api/Dockerfile
    container_name: local-api
    env_file:
      - .env.development
    restart: always
    ports:
      - '3001:3001'
  client:
    build:
      context: ./
      dockerfile: ./packages/client/Dockerfile
    container_name: local-client
    env_file:
      - .env.development
    restart: always
    ports:
      - '3000:3000'
  database:
    build:
      context: ./
      dockerfile: ./packages/database/Dockerfile
    container_name: local-database
    env_file:
      - .env.development
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
